### ISSUE TITLE
Collect basic information about Debian Linux

### ISSUE THREAD

**Issue by fschrogl** [fschrogl/infra-automation#15]
I decided on using Debian on my server, but I never really used Debian before. So it's time to get to know Debian a but and thus to read and collect information about it.

- [Debian Admin Handbook](https://www.debian.org/doc/manuals/debian-handbook/)
- [Debian Reference](https://www.debian.org/doc/manuals/debian-reference/)
- [Debian Wiki](https://wiki.debian.org/)

### Tasks

- **Debian Handbook**
  - [x] Chapter 1: Lifecycle of a Release
  - [x] Chapter 5: Packaging System
  - [ ] Chapter 6: Maintenance and Updates
  - [ ] Chapter 8: Basic System Configuration
  - [ ] Chapter 9: Unix Services
  - [ ] Chapter 10: Networking
  - [ ] Chapter 11: Network Services
  - [ ] Chapter 12: Administration
  - [ ] Chapter 14: Security

- **Debian Reference**
  - [ ] Chapter 2: Package Management
  - [ ] Chapter 3: System Boot
  - [ ] Chapter 4: Authentication and Access Control
  - [ ] Chapter 5: Network Setup
  - [ ] Chapter 6: Network Services
  - [ ] Chapter 8: Localisation
  - [ ] Chapter 9: Tips
